site_name: Chaos Toolkit
site_author: The chaostoolkit Team
site_description: Chaos Toolkit
copyright: '&copy; 2017 chaostoolkit team'
theme: material
docs_dir: sources
google_analytics:
  - UA-107338053-1
  - auto
repo_name: chaostoolkit
repo_url: https://github.com/chaostoolkit/chaostoolkit
markdown_extensions:
  - markdown_include.include:
      base_path: "sources/shared"
  - admonition
  - codehilite(guess_lang=false, linenums=false)
  - def_list
  - footnotes
  - meta
  - smarty
  - toc(permalink=true)
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
extra:
  palette:
    primary: blue-grey
    accent: blue-grey
  social:
    - type: github
      link: https://github.com/chaostoolkit
    - type: twitter
      link: https://twitter.com/chaostoolkit
    - type: slack
      link: https://join.chaostoolkit.org/
pages:
- Overview:
    - Introduction: index.md
    - Concepts: overview/concepts.md
    - FAQ: faq.md
- Getting Started:
    - Install: usage/install.md
    - Upgrade: usage/upgrade.md
    - Run: usage/running.md
    - Tutorials: usage/tutorial.md
    - Latest Release: usage/latest.md
- Technology:
    - Overview: technology/index.md
    - Experiment: technology/experiment.md
    - Extend: technology/extend.md