site_name: ""
site_url: "https://chaostoolkit.org"
use_directory_urls: true
site_author: The Chaos Toolkit Team
site_description: Chaos Toolkit
copyright: '&copy; 2017-2021 Chaos Toolkit team'
edit_uri: ""
theme:
  name: material
  favicon: "static/images/favicon.ico"
  logo: "static/images/chaos-toolkit-full.svg"
  palette:
    primary: white
    accent: yellow
  custom_dir: sources/overrides
  include_search_page: false
  search_index_only: true
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
extra_css:
  - 'static/css/extra.css'
docs_dir: sources
# wait until new release of material is pushed out
# see https://www.mkdocs.org/about/release-notes/#backward-incompatible-changes-in-12
#google_analytics:
#  - UA-107338053-1
#  - auto
repo_name: chaostoolkit
repo_url: https://github.com/chaostoolkit/chaostoolkit
markdown_extensions:
  - markdown_include.include:
      base_path: "sources/shared"
  - admonition
  - def_list
  - footnotes
  - meta
  - smarty
  - toc:
      permalink: True
  - pymdownx.betterem:
      smart_enable: "all"
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: True
  - pymdownx.tilde
plugins:
  - search
  - minify:
      minify_html: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chaostoolkit
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/chaostoolkit
    - icon: fontawesome/brands/slack
      link: https://join.chaostoolkit.org/
    - icon: fontawesome/brands/medium
      link: https://medium.com/chaos-toolkit
nav:
- Home: index.md
- Get Started:
    - Install: reference/usage/install.md
    - Upgrade: reference/usage/upgrade.md
    - CLI:
        - Overview: reference/usage/cli.md
        - Discover: reference/usage/discover.md
        - Init: reference/usage/init.md
        - Run: reference/usage/run.md
        - Report: reference/usage/report.md
        - Notifications: reference/usage/notification.md
        - Schedule: reference/usage/scheduling.md
- Guides:
    - Get Started with the Chaos Toolkit: reference/tutorial.md
    - Author and Operator: reference/tutorials/authoring_operating.md
    - Understand the Execution Flow: reference/tutorials/run-flow.md
    - Learn all about Steady-State Tolerances: reference/tutorials/tolerance.md
    - An overview of extending the Chaos Toolkit: reference/tutorials/extend.md
    - Experimenting against a blockchain: reference/tutorials/blockchain.md
- Reference:
    - API:
      - Concepts: reference/concepts.md
      - Experiment: reference/api/experiment.md
      - Journal: reference/api/journal.md
    - CLI:
        - Overview: reference/usage/cli.md
        - Discover: reference/usage/discover.md
        - Init: reference/usage/init.md
        - Run: reference/usage/run.md
        - Report: reference/usage/report.md
        - Notifications: reference/usage/notification.md
        - Schedule: reference/usage/scheduling.md
    - Extensions:
        - Overview: drivers/overview.md
        - Infrastructure/Platform:
          - AWS: drivers/aws.md
          - Ansible: drivers/ansible.md
          - Azure: drivers/azure.md
          - Cloud Foundry: drivers/cloudfoundry.md
          - Gandi: drivers/gandi.md
          - Google Cloud Platform: drivers/gcp.md
          - Kubernetes: drivers/kubernetes.md
          - Service Fabric: drivers/service-fabric.md
        - Application:
          - Spring: drivers/spring.md
        - Network:
          - ToxiProxy: drivers/toxiproxy.md
          - Istio: drivers/istio.md
          - WireMock: drivers/wiremock.md
        - Load Testing:
          - k6: drivers/k6.md
        - Observability:
          - Humio: drivers/humio.md
          - Prometheus: drivers/prometheus.md
          - Open Tracing: drivers/opentracing.md
          - Dynatrace: drivers/dynatrace.md
        - Reliability:
          - Reliably: drivers/reliably.md
    - Deployment:
        - Kubernetes:
            - Operator: deployment/k8s/operator.md
    - Develop:
      - Guidelines: reference/developing/guidelines.md
      - Driver Extension:
          - Extension Approaches: reference/extending/approaches.md
          - Extend with Python: reference/extending/extending-with-python.md
      - Control Extension:
          - Create Control: reference/extending/create-control-extension.md
- Contribute:
    - Contributing to the Chaos Toolkit: reference/contributing.md
    - Project Management:
        - Key Project Values: reference/developing/values.md
        - Core Projects: reference/developing/core.md
        - Extensions Projects: reference/developing/extensions.md
        - Technology Choices: reference/developing/technologies.md
    - Resources:
      - Logos: resources/logos.md
      - Slides: resources/slides.md
