site_name: Chaos Toolkit
site_author: The chaostoolkit Team
site_description: Chaos Toolkit
copyright: '&copy; 2017 chaostoolkit team'
theme: material
docs_dir: sources
google_analytics:
  - UA-107338053-1
  - auto
repo_name: chaostoolkit
repo_url: https://github.com/chaostoolkit/chaostoolkit
markdown_extensions:
  - markdown_include.include:
      base_path: "sources/shared"
  - admonition
  - codehilite(guess_lang=false, linenums=false)
  - def_list
  - footnotes
  - meta
  - smarty
  - toc(permalink=true)
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
extra:
  palette:
    primary: blue-grey
    accent: blue-grey
  social:
    - type: github
      link: https://github.com/chaostoolkit
    - type: twitter
      link: https://twitter.com/chaostoolkit
    - type: slack
      link: https://join.chaostoolkit.org/
    - type: medium
      link: https://medium.com/chaos-toolkit
pages:
- Home: index.md
- New to Chaos Engineering: new-to-chaos.md
- Getting Started with the Tutorials: getting-started.md
- Explore Specific Use Cases: explore-specific-cases.md
- Explore Third Party and Commercial Integrations: integrations.md
- Contributing to the Chaos Toolkit: contributing.md
- Contributors & Sponsors: contributors.md
- FAQ: faq.md
- Reference:
    - Introduction: reference/introduction.md
    - Concepts: reference/concepts.md
    - The Chaos Toolkit Workflow: reference/workflow.md
    - Usage:
        - Overview: reference/usage/overview.md
        - Install: reference/usage/install.md
        - Upgrade: reference/usage/upgrade.md
        - The CLI: reference/usage/cli.md
        - Settings: reference/usage/settings.md
        - Discover: reference/usage/discover.md
        - Init: reference/usage/init.md
        - Run: reference/usage/run.md
        - Report: reference/usage/report.md
        - Notification: reference/usage/notification.md
    - Open API:
        - Experiment: reference/api/experiment.md
        - Journal: reference/api/journal.md
    - Extending Chaos Toolkit:
        - Extension Approaches: reference/extending/approaches.md
        - Python: reference/extending/extending-with-python.md
    - Developing Chaos Toolkit:
        - Key Project Values: reference/developing/values.md
        - Core Projects: reference/developing/core.md
        - Extensions: reference/developing/extensions.md
        - Technology Choices: reference/developing/technologies.md
        - Guidelines: reference/developing/guidelines.md

